### ISSUE TITLE
Issue with video liked

### ISSUE THREAD

**Issue by jeanpages** [neuro-sys/tumblr-likes-downloader#43]
Hello, first of all your app is really amazing, thank you very much for your work!
But there is an issue when it download videos. 

<img width="1440" alt="capture d ecran 2018-12-09 a 20 54 17" src="https://user-images.githubusercontent.com/45691153/49702240-53b99d00-fbf6-11e8-9828-0e2a81400277.png">

As you can see in the picture, for one video the app tries to download it 3 times (and skip the download 2 times I don't know if it's normal). In the end the video file I get is a mp4 that weight 157Ko and that can't be opened.
It is the same for all the videos.

I use the 0.0.2 release.

Thanks again.

**Comment by Viraha** [comment]
I have a simil problem. I used the 0.0.1 release. It downloaded everything perfectly until it stopped because of this: 

There was an error:
Get https://clqrkkent.tumblr.com/video_file/t:WEz2YoaC3vC19HmZ-skp1A/175472377011/tumblr_o8h1ls6ns91qznjkl: dial tcp: lookup clqrkkent.tumblr.com: no such host
* Finished...

Thank you for your work!

**Comment by neuro-sys** [comment]
I fixed the video issue in the release 0.0.3. Also added a Start Offset option to specify the point at which to start downloading likes.
