### ISSUE TITLE
I can only get it to download someone's posts, not likes.

### ISSUE THREAD

**Issue by ChameleonQuest** [neuro-sys/tumblr-likes-downloader#46]
There is a prompt for "blog name". So I can enter someone blog and it downloads everything they ever posted. I thought maybe it would download only the things I liked from that blog but the app is downloading everything from them.

I'm interested in downloading my "likes", not posts. I don't actually post anything.  When I enter my likes-url, the app doesn't work.  And even the "blog name" prompt doesn't seem to expect a like-url.

Am I missing something obvious?

**Comment by BlisteringSyko** [comment]
i just put in my blog url and api key, downloads fine till it hits the api limit. 
The blog url needs to be for the same blog that your api key is for. so blogname.tumblr.com
No https or anything before it. Doesnt needs to be the url for the likes, just the blog.

**Comment by neuro-sys** [comment]
I changed the wording in the current latest release. Instead of "Blog Name", now it asks for "User Name", without the blog URL. It's supposed to download all the likes one's user has, not someone else's likes -- although I am not entirely sure how Tumblr API behaves in that case for everyone else. If I request someone else's blog/user-name, I get the following error:

```
[DEBUG] - {
  "errors": [
    {
      "code": 0,
      "detail": "Tumblr went thud. Try again.",
      "title": "Forbidden"
    }
  ],
  "meta": {
    "msg": "Forbidden",
    "status": 403
  },
  "response": []
}
```

As this is all expected, I'm closing this one.
